---
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Check if networks exist
  command: docker network inspect {{ item }}
  register: network_check
  failed_when: network_check.rc != 0
  changed_when: false
  loop: 
    - traefik_proxy
    - pangolin_network

- name: Create directories for NZBget
  file:
    path: "{{ item }}"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: "0755"
  loop:
    - "{{ nzbget_config }}"
    - "{{ media_data_path }}"
    - "{{ media_data_path }}/downloads"
    - "{{ media_data_path }}/downloads/nzbget"
    - "{{ media_data_path }}/downloads/nzbget/completed" 
    - "{{ media_data_path }}/downloads/nzbget/completed/Movies"
    - "{{ media_data_path }}/downloads/nzbget/completed/Series"
    - "{{ media_data_path }}/downloads/nzbget/incomplit"
    - "{{ media_data_path }}/downloads/nzbget/torrent"

- name: Deploy NZBGet container
  docker_container:
    name: nzbget
    image: lscr.io/linuxserver/nzbget:latest
    user: "nobody:nogroup"
    env:
      PUID: "65534"
      PGID: "65534"
      TZ: "GB"
      NZBGET_USER: "{{ nzbget_username }}"
      NZBGET_PASS: "{{ nzbget_password }}"
    volumes:
      - "{{ nzbget_config }}:/config"
      - "{{ media_data_path }}/downloads/nzbget:/downloads"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "nzbget"
      traefik.enable: "true"
      traefik.http.routers.nzbget-secure.entrypoints: "https"
      traefik.http.routers.nzbget-secure.rule: "Host(`{{ nzbget_domain }}`)"
      traefik.http.routers.nzbget-secure.tls: "true"
      traefik.http.routers.nzbget.service: "nzbget"
      traefik.http.services.nzbget.loadbalancer.server.port: "6789"
      traefik.docker.network: "traefik_proxy"
      # tsdproxy.enable: "true"
      # tsdproxy.name: "nzbget"
      # tsdproxy.scheme: "http"
      # tsdproxy.tlsvalidate: "false"
      # tsdproxy.container_port: "6789"
    networks:
      - name: traefik_proxy
      - name: pangolin_network
    restart_policy: unless-stopped
    state: started

- name: Fix folder ownership
  shell: "sudo docker exec -it nzbget chown nobody:nogroup {{ item }}"
  loop:
    - "/downloads/completed"
    - "/downloads/incomplit"
    - "/downloads/torrent"

- name: NZBget deployed
  debug:
    msg: "NZBget is running successfully"
