- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Check if networks exist
  command: docker network inspect {{ item }}
  register: network_check
  failed_when: network_check.rc != 0
  changed_when: false
  loop: 
    - traefik_proxy
    - pangolin_network

- name: Create directories for Prowlarr
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0755"
  loop:
    - "{{ prowlarr_config }}"

- name: Deploy Prowlarr container
  docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "GB"
    volumes:
      - "{{ prowlarr_config }}:/config"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "prowlarr"
      traefik.enable: "true"
      traefik.http.routers.prowlarr-secure.entrypoints: "https"
      traefik.http.routers.prowlarr-secure.rule: "Host(`{{ prowlarr_domain }}`)"
      traefik.http.routers.prowlarr-secure.tls: "true"
      traefik.http.routers.prowlarr.service: "prowlarr"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
      traefik.docker.network: "traefik_proxy"
      # tsdproxy.enable: "true"
      # tsdproxy.name: "prowlarr"
      # tsdproxy.scheme: "http"
      # tsdproxy.tlsvalidate: "false"
      # tsdproxy.container_port: "9696"
    networks:
      - name: traefik_proxy
      - name: pangolin_network
    restart_policy: unless-stopped
    state: started

- name: Prowlarr deployed
  debug:
    msg: "Prowlarr is running successfully"
