- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Check if networks exist
  command: docker network inspect {{ item }}
  register: network_check
  failed_when: network_check.rc != 0
  changed_when: false
  loop: 
    - traefik_proxy
    - pangolin_network

- name: Deploy Lunasea container
  docker_container:
    name: lunasea
    image: ghcr.io/jagandeepbrar/lunasea:stable
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "lunasea"
      traefik.enable: "true"
      traefik.http.routers.lunasea-secure.entrypoints: "https"
      traefik.http.routers.lunasea-secure.rule: "Host(`{{ lunasea_domain }}`)"
      traefik.http.routers.lunasea-secure.tls: "true"
      traefik.http.routers.lunasea.service: "lunasea"
      traefik.http.services.lunasea.loadbalancer.server.port: "80"
      traefik.docker.network: "traefik_proxy"
      # tsdproxy.enable: "true"
      # tsdproxy.name: "lunasea"
      # tsdproxy.scheme: "http"
      # tsdproxy.tlsvalidate: "false"
      # tsdproxy.container_port: "80"
    networks:
      - name: traefik_proxy
      - name: pangolin_network
    restart_policy: always
    tty: yes
    interactive: yes
    state: started

- name: Lunasea deployed
  debug:
    msg: "Lunasea is running successfully"
