---
- name: Install Samba
  apt:
    name: samba
    state: present

- name: Ensure users exist
  user:
    name: "{{ item.username }}"
    state: present
  loop: "{{ shares }}"

- name: Ensure Samba users exist
  command: "smbpasswd -a {{ item.username }}"
  args:
    stdin: "{{ item.password }}\n{{ item.password }}"
  changed_when: false
  loop: "{{ shares }}"

- name: Ensure Samba users are enabled
  command: "smbpasswd -e {{ item.username }}"
  changed_when: false
  loop: "{{ shares }}"

- name: Ensure shared directories exist
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0777'
  loop: "{{ shares }}"

- name: Ensure Samba share configurations are present
  blockinfile:
    path: /etc/samba/smb.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.name }}"
    block: |
      [{{ item.name }}]
      path = {{ item.path }}
      browseable = yes
      guest ok = {{ item.guest_ok }}
      writeable = {{ item.writeable }}
      public = {{ item.public }}
      {% if not item.guest_ok | bool %}
        valid users = {{ item.username }}
      {% endif %}
  loop: "{{ shares }}"
  notify: Restart Samba

