---
# - name: Ensure Docker service is running and setup user access
#   include_role:
#     name: common
#     tasks_from: setup_docker_user
#   vars:
#     target_user: "{{ docker_user }}"

- name: Ensure docker networks exist
  community.docker.docker_network:
    name: "{{ network_item }}"
    state: present
  loop:
    - traefik_proxy
    - pangolin_network
    - kleovate_network
  loop_control:
    loop_var: network_item

- name: Get user information
  getent:
    database: passwd
    key: "{{ docker_user }}"

- name: Set UID and GID facts
  set_fact:
    target_uid: "{{ getent_passwd[docker_user][1] }}"
    target_gid: "{{ getent_passwd[docker_user][2] }}"
  
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ target_uid}}"
    group: "{{ target_gid }}"
    recurse: true
    mode: "0755"
  loop:
    - "{{ authenticator_config }}"

- name: Configure appsettings.json for Kleovate Authenticator
  template:
    src: appsettings.json.j2
    dest: "{{ authenticator_config }}/appsettings.json"
    owner: "{{ target_uid}}"
    group: "{{ target_gid }}"
    mode: '0644'

- name: Log in to GitHub Container Registry (GHCR)
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ github_username }}"
    password: "{{ local_github_pat }}"
    reauthorize: true

- name: Pull the .NET 10 Docker image from GHCR
  community.docker.docker_image:
    name: "{{ image_url }}"
    source: pull
    # Forcing pull ensures you get the latest version of the tag
    force_source: true

- name: Run the .NET 10 Docker container
  community.docker.docker_container:
    name: KleovateAuthenticator
    image: "{{ image_url }}"
    hostname: KleovateAuthenticator
    user: "{{ target_uid }}:{{ target_gid }}"
    # ports:
    #   - "{{ host_port }}:8080"
    volumes:
      - "{{ authenticator_config }}/appsettings.json:/app/appsettings.json:ro"
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
    labels:
      com.docker.compose.project: "kleovate_stack"
      com.docker.compose.service: "KleovateAuthenticator"
      traefik.enable: "true"
      traefik.http.routers.authenticator-secure.entrypoints: "https"
      traefik.http.routers.authenticator-secure.rule: "Host(`{{ authenticator_domain }}`)"
      traefik.http.routers.authenticator-secure.tls: "true"
      traefik.http.routers.authenticator-secure.service: "authenticator"
      traefik.http.services.authenticator.loadbalancer.server.port: "8080"
      traefik.docker.network: "traefik_proxy" 
    networks:
      - name: traefik_proxy
      - name: pangolin_network
      - name: kleovate_network
    restart_policy: always
    state: started

- name: Log out of GHCR (Cleanup)
  community.docker.docker_login:
    registry_url: ghcr.io
    state: absent
