---
- name: Install matrix-nio dependency
  apt:
    name: python3-matrix-nio

- name: Deploy Matrix Notification Script from Template
  ansible.builtin.template:
    src: matrix_notify.py.j2
    dest: "{{ notify_script_path }}"
    mode: "0755"
  vars:
    homeserver_url: "{{ matrix_homeserver_url }}"
    room_id: "{{ matrix_room_id }}"
    bot_username: "{{ matrix_bot_username }}"
    access_token: "{{ matrix_access_token }}"

- name: Get existing cron jobs
  command: crontab -l
  register: cron_jobs
  ignore_errors: true
  changed_when: false

- name: Make sure the script is not already added.
  set_fact:
    not_exists: "{{ notify_script_path not in cron_jobs.stdout }}"

- name: Replace multiple spaces with newline and save output
  set_fact:
    updated_cron_jobs: "{{ cron_jobs.stdout | regex_replace('\\s{2,}', '\\n') }}"
  when: not_exists

- name: Backup existing crontab
  copy:
    content: "{{ updated_cron_jobs }}"
    dest: "/root/crontab_backup"
  when: 
    - not_exists
    - updated_cron_jobs != ""
  changed_when: false

- name: Update cron jobs to new format
  set_fact: 
     cron_jobs_with_notification: "{{ updated_cron_jobs.splitlines() | map('regex_replace', '^(?!#)(\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+\\S+)\\s*(.+)', '\\1 ( \\2 2>&1 ; echo \"EXIT:\\$?\" ) | python3 ' + notify_script_path + ' \\\"Cron Job Status\\\"') | join('\n') }}"
  when: not_exists

# - name: debug
#   debug:
#     var: cron_jobs_with_notification

- name: Update cron jobs to new format
  shell: |
    echo "{{ cron_jobs_with_notification }}" | crontab -
  when: 
    - not_exists
    - cron_jobs_with_notification != ""
