forgejo_base_path: "{{ base_app_storage_path }}/forgejo"
forgejo_data_dir: "{{ forgejo_base_path }}/data"

forgejo_local_dir: "{{ base_local_ssd_storage_path }}/forgejo"
forgejo_runner_data_dir: "{{ forgejo_local_dir }}/runner"
postgres_data_dir: "{{ forgejo_local_dir }}/forgejodb"
forgejo_backup_scripts: "{{ forgejo_local_dir }}/db_backup_scripts"

forgejo_db_name: "forgejo_db"
forgejo_db_user: "{{ vm_username }}"
forgejo_db_password: "{{ vm_password }}"

forgejo_domain: "forgejo.{{ subdomain }}"
forgejo_url: "https://{{ forgejo_domain }}"

forgejo_runner_uuid: "ad3a9dce-f651-4b4a-8ea5-566909a7ae34"
forgejo_runner_token: "e63b1e4d6a28038734b2b56ff435899575ec74be"

server_ip_address: "192.168.8.3"

forgejo_backup_db: false
forgejo_restore_db: false
